### PR TITLE
remove deprecated code without extra dependency

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by schriftgestalt** [comment]
It would be great if that could be merge as soon as possible. I’m getting a lot crash reports because of this.

**Comment by justvanrossum** [comment]
Note that we have releases on PyPI and release tags: https://github.com/robotools/vanilla/tags.

You should not install directly from the head of the repo.

**Comment by schriftgestalt** [comment]
But Glyphs does manage (install and update) all plugins using git. Using pip (and PyPI) would be much works for all those plugins and the tags for vanilla are from last year, so not really up to date. 

I would consider the main branch of any repo to be stable to use for regular users. Maybe do commits like this on a dev branch?

**Comment by justvanrossum** [comment]
No, only release tags are considered stable.

Do you also install (for example) fonttools from the head of the repo?

**Comment by justvanrossum** [comment]
Btw. the real bug is that `packaging` isn't declared as a dependency in `setup.py`. But I bet that wouldn't have helped the Glyphs problem, given you don't appear to use pip at all. You really should!

Frederik is currently travelling, and I'm not going to merge this without his review.

**Comment by schriftgestalt** [comment]
I better understand the intended behavior now and will find a solution. I probably will point Glyphs to a fork that I can control.

**Comment by justvanrossum** [comment]
Tip: DrawBot contains a pip installer with GUI, but that code can also be used as an example of how to use pip programmatically: https://github.com/typemytype/drawbot/blob/master/drawBot/pipInstaller.py

**Comment by benkiel** [comment]
I am ok with this change.

**Comment by typemytype** [comment]
thanks Georg!

**Pull request merged**
