### PR TITLE
various updates to the docs

### PR DESCRIPTION
**Pull request by gferreira**
hi guys, sorry for polluting the commit history.

I’m trying to figure out why most of the docs is not building correctly in RTD (thanks Ben for giving me access). it takes some trial and error… can we use a separate branch for testing?

I’ve now added a config file for ReadTheDocs, following the instructions [here](http://docs.readthedocs.io/en/stable/config-file/v2.html). I can see that the RTD build is using py2.7, maybe that’s what is causing problems? – I’ve set it to 3.7 in the `.readthedocs.yml`.

not sure if we need to specify any dependencies, all the NSObjects are already mocked…

edit: just to be clear, please don’t merge this in master, but in a separate branch (for ex: `docs`) so we can test it with RTD.

### CODE REVIEW

**Comment by gferreira** [comment]
looking at the RTD log, this is the error that keeps popping up:
```
    if osVersionCurrent >= osVersion10_10:
  File "/home/docs/.pyenv/versions/2.7.16/lib/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'
```

**Comment by benkiel** [comment]
@gferreira made a doc brand, can you change your PR to that branch?

**Comment by benkiel** [comment]
@gferreira set up RTD to build this branch too.

**Comment by benkiel** [comment]
@gferreira looks like that may have fixed it!

**Comment by gferreira** [comment]
hello @benkiel, thanks for setting up a test branch.

it’s not really working yet – all pages after Sheet are empty, and screenshots are not showing up. but now we can make some tests without making a mess :) I’ll give it another shot soon.

**Comment by typemytype** [comment]
maybe its a good plan to jump to RTD py3 sphinx

But Im unaware of the changed this would bring, but py3 is more future proof

**Pull request merged**
